apiVersion: v1
kind: Template
metadata:
  name: 3scale-gateway
  annotations:
    openshift.io/documentation-url: https://access.redhat.com/documentation/en-us/red_hat_3scale/2.saas/html/deployment_options/apicast-openshift
    openshift.io/display-name: 3scale APIcast API Gateway
    openshift.io/provider-display-name: Red Hat, Inc.
    iconClass: icon-3scale
    description: >-
      3scale's APIcast is an NGINX based API gateway used to integrate your internal and external
      API services with 3scale's API Management Platform. It supports OpenID connect to integrate
      with external Identity Providers such as Red Hat Single Sign On, for API traffic authentication
    tags: api,gateway,3scale
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${APICAST_NAME}"
  spec:
    replicas: 1
    selector:
      deploymentconfig: "${APICAST_NAME}"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: "${APICAST_NAME}"
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port: '9421'
      spec:
        containers:
        - env:
          - name: THREESCALE_PORTAL_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: "${CONFIGURATION_URL_SECRET}"
                key: password
          - name: THREESCALE_CONFIG_FILE
            value: "${CONFIGURATION_FILE_PATH}"
          - name: THREESCALE_DEPLOYMENT_ENV
            value: "${DEPLOYMENT_ENVIRONMENT}"
          - name: RESOLVER
            value: "${RESOLVER}"
          - name: APICAST_SERVICES_LIST
            value: "${SERVICES_LIST}"
          - name: APICAST_CONFIGURATION_LOADER
            value: "${CONFIGURATION_LOADER}"
          - name: APICAST_LOG_LEVEL
            value: "${LOG_LEVEL}"
          - name: APICAST_PATH_ROUTING
            value: "${PATH_ROUTING}"
          - name: APICAST_RESPONSE_CODES
            value: "${RESPONSE_CODES}"
          - name: APICAST_CONFIGURATION_CACHE
            value: "${CONFIGURATION_CACHE}"
          - name: REDIS_URL
            value: "${REDIS_URL}"
          - name: APICAST_MANAGEMENT_API
            value: "${MANAGEMENT_API}"
          - name: OPENSSL_VERIFY
            value: "${OPENSSL_VERIFY}"
          - name: APICAST_EXTENDED_METRICS
            value: "${EXTENDED_METRICS}"
          image: ${AMP_APICAST_IMAGE}
          imagePullPolicy: IfNotPresent
          name: "${APICAST_NAME}"
          livenessProbe:
            httpGet:
              path: /status/live
              port: management
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /status/ready
              port: management
            initialDelaySeconds: 15
            timeoutSeconds: 1
          ports:
          - name: proxy
            containerPort: 8080
            protocol: TCP
          - name: management
            containerPort: 8090
            protocol: TCP
          - name: metrics
            containerPort: 9421
            protocol: TCP
          resources:
            limits:
                cpu: '1'
                memory: 128Mi
            requests:
                cpu: 500m
                memory: 64Mi

        - env:
          name: mock-rest
          image: 172.30.1.1:5000/openshift/mock-rest
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 7070
            protocol: TCP
          volumeMounts:
          - mountPath: /data/admin/api/services/44/proxy/configs/staging/
            name: mock-rest-admin
          - mountPath: /data/transactions
            name: mock-rest-transactions
          - mountPath: /data/admin/api
            name: mock-rest-services

        volumes:
        - name: mock-rest-admin
          configMap:
            name: mock-rest-admin-config
        - name: mock-rest-transactions
          configMap:
            name: mock-rest-transactions-config
        - name: mock-rest-services
          configMap:
            name: mock-rest-services-config
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mock-rest-services-config
  data:
    services.json: |-
      {
          "services": [
              {
                  "service": {
                      "backend_version": "1",
                      "buyer_can_select_plan": false,
                      "buyer_key_regenerate_enabled": true,
                      "buyer_plan_change_permission": "request",
                      "buyers_manage_apps": true,
                      "buyers_manage_keys": true,
                      "created_at": "2020-09-04T16:09:18-03:00",
                      "custom_keys_enabled": true,
                      "deployment_option": "hosted",
                      "description": "Echo",
                      "end_user_registration_required": true,
                      "id": 44,
                      "intentions_required": false,
                      "links": [
                          {
                              "href": "https://dev-admin.3scale.apps.openshift.ase.local/admin/api/services/44/metrics",
                              "rel": "metrics"
                          },
                          {
                              "href": "https://dev-admin.3scale.apps.openshift.ase.local/admin/api/services/44/end_user_plans",
                              "rel": "end_user_plans"
                          },
                          {
                              "href": "https://dev-admin.3scale.apps.openshift.ase.local/admin/api/services/44",
                              "rel": "self"
                          },
                          {
                              "href": "https://dev-admin.3scale.apps.openshift.ase.local/admin/api/services/44/service_plans",
                              "rel": "service_plans"
                          },
                          {
                              "href": "https://dev-admin.3scale.apps.openshift.ase.local/admin/api/services/44/application_plans",
                              "rel": "application_plans"
                          },
                          {
                              "href": "https://dev-admin.3scale.apps.openshift.ase.local/admin/api/services/44/features",
                              "rel": "features"
                          }
                      ],
                      "mandatory_app_key": true,
                      "name": "Echo",
                      "referrer_filters_required": false,
                      "state": "incomplete",
                      "support_email": "dev@medife.com.ar",
                      "system_name": "echo",
                      "updated_at": "2020-09-04T16:11:43-03:00"
                  }
              }
          ]
      }

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mock-rest-transactions-config
  data:
    authrep.xml: |-
      <?xml version="1.0" encoding="UTF-8"?><status><authorized>true</authorized><plan>basic</plan></status>

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mock-rest-admin-config
  data:
    latest.json: |-
      {
          "proxy_config": {
              "content": {
                  "account_id": 4,
                  "act_as_product": 0,
                  "admin_support_email": null,
                  "backend_authentication_type": "service_token",
                  "backend_authentication_value": "6f0bda11deb3f97cadf77525e6c64f8eeebc6e06f8cd447ba26272cbe8120a66",
                  "backend_version": "1",
                  "buyer_can_select_plan": false,
                  "buyer_key_regenerate_enabled": true,
                  "buyer_plan_change_permission": "request",
                  "buyers_manage_apps": true,
                  "buyers_manage_keys": true,
                  "created_at": "2020-09-04T16:09:18-03:00",
                  "credit_card_support_email": null,
                  "custom_keys_enabled": true,
                  "default_application_plan_id": null,
                  "default_end_user_plan_id": null,
                  "default_service_plan_id": null,
                  "deployment_option": "hosted",
                  "description": "Echo",
                  "display_provider_keys": false,
                  "draft_name": "",
                  "end_user_registration_required": true,
                  "id": 44,
                  "infobar": null,
                  "intentions_required": false,
                  "kubernetes_service_link": null,
                  "logo_content_type": null,
                  "logo_file_name": null,
                  "logo_file_size": null,
                  "mandatory_app_key": true,
                  "name": "Echo",
                  "notification_settings": null,
                  "oneline_description": null,
                  "proxiable?": true,
                  "proxy": {
                      "api_backend": "http://example1.app-project1.svc:8080",
                      "api_test_path": "/",
                      "api_test_success": null,
                      "apicast_configuration_driven": true,
                      "auth_app_id": "app_id",
                      "auth_app_key": "app_key",
                      "auth_user_key": "user_key",
                      "authentication_method": "1",
                      "backend": {
                          "endpoint": "http://mock-rest-app-project1.192.168.64.14.nip.io:80",
                          "host": "mock-rest-app-project1.192.168.64.14.nip.io"
                      }
                      "created_at": "2020-09-04T16:09:18-03:00",
                      "credentials_location": "query",
                      "deployed_at": null,
                      "endpoint": "http://apicast-staging-app-project1.192.168.64.14.nip.io:80",
                      "endpoint_port": 80,
                      "error_auth_failed": "Authentication  failed",
                      "error_auth_missing": "Authentication parameters missing",
                      "error_headers_auth_failed": "text/plain; charset=us-ascii",
                      "error_headers_auth_missing": "text/plain; charset=us-ascii",
                      "error_headers_limits_exceeded": "text/plain;  charset=us-ascii",
                      "error_headers_no_match": "text/plain; charset=us-ascii",
                      "error_limits_exceeded": "Usage limit exceeded",
                      "error_no_match": "No Mapping Rule matched",
                      "error_status_auth_failed": 403,
                      "error_status_auth_missing": 403,
                      "error_status_limits_exceeded": 429,
                      "error_status_no_match": 404,
                      "hostname_rewrite": "",
                      "hostname_rewrite_for_sandbox": "example1.app-project1.svc",
                      "hosts": [
                          "apicast-staging-app-project1.192.168.64.14.nip.io",
                          "apicast-staging-app-project1.192.168.64.14.nip.io"
                      ],
                      "id": 44,
                      "jwt_claim_with_client_id": null,
                      "jwt_claim_with_client_id_type": null,
                      "lock_version": 2,
                      "oauth_login_url": null,
                      "oidc_issuer_endpoint": null,
                      "oidc_issuer_type": "keycloak",
                      "policy_chain": [
                          {
                              "configuration": {},
                              "name": "apicast",
                              "version": "builtin"
                          }
                      ],
                      "production_domain": "apicast-staging-app-project1.192.168.64.14.nip.io",
                      "proxy_rules": [
                          {
                              "created_at": "2020-09-04T16:09:18-03:00",
                              "delta": 1,
                              "http_method": "POST",
                              "id": 413,
                              "last": false,
                              "metric_id": 323,
                              "metric_system_name": "hits",
                              "owner_id": 44,
                              "owner_type": "Proxy ",
                              "pattern": "/api/say",
                              "position": 1,
                              "proxy_id": 44,
                              "redirect_url": null,
                              "tenant_id": 4,
                              "updated_at": "2020-09-04T16:10:01-03:00"
                          }
                      ],
                      "sandbox_endpoint": "http://apicast-staging-app-project1.192.168.64.14.nip.io:80",
                      "secret_token": "Shared_secret_sent_from_proxy_to_API_backend_a0bc7cfabd000bef",
                      "service_backend_version": "1",
                      "service_id": 44,
                      "staging_domain": "apicast-staging-app-project1.192.168.64.14.nip.io",
                      "tenant_id": 4,
                      "updated_at": "2020-09-04T16:11:43-03:00",
                      "valid?": true
                  },
                  "referrer_filters_required": false,
                  "state": "incomplete",
                  "support_email": "dev@medife.com.ar",
                  "system_name": "echo",
                  "tech_support_email": null,
                  "tenant_id": 4,
                  "terms": null,
                  "txt_api": null,
                  "txt_features": null,
                  "txt_support": null,
                  "updated_at": "2020-09-04T16:11:43-03:00"
              },
              "environment": "sandbox",
              "id": 356,
              "version": 1
          }
      }


- apiVersion: v1
  kind: Secret
  metadata:
    name: apicast-configuration-url-secret
  stringData:
    password: "http://c305ade34d4b720fa1ccfe3bfdfa0bb30c2764b108e9187063d663a7fa935016@mock-rest-app-project1.192.168.64.14.nip.io"

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: mock-rest
    name: mock-rest
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      deploymentconfig: "${APICAST_NAME}"

- apiVersion: v1
  kind: Service
  metadata:
    name: "${APICAST_NAME}"
  spec:
    ports:
    - name: proxy
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: management
      port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      deploymentconfig: "${APICAST_NAME}"

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APICAST_NAME}
    name: ${APICAST_NAME}
  spec:
    port:
      targetPort: proxy
    to:
      name: ${APICAST_NAME}
      weight: 100
    wildcardPolicy: None

parameters:
- name: AMP_RELEASE
  description: "AMP release tag."
  value: "2.9.0"
  required: true
- name: AMP_APICAST_IMAGE
  value: "172.30.1.1:5000/openshift/apicast-gateway-rhel7"
  required: true
- description: "Name of the secret containing the THREESCALE_PORTAL_ENDPOINT with the access-token or provider key"
  value: apicast-configuration-url-secret
  name: CONFIGURATION_URL_SECRET
  required: true
- description: "Path to saved JSON file with configuration for the gateway. Has to be injected to the container image as read only volume."
  name: CONFIGURATION_FILE_PATH
  required: false
- description: "Deployment environment. Can be staging or production."
  value: production
  name: DEPLOYMENT_ENVIRONMENT
  required: true
- description: "Name for the 3scale API Gateway"
  value: apicast
  name: APICAST_NAME
  required: true
- description: "DNS Resolver for openresty, if empty it will be autodiscovered"
  value:
  name: RESOLVER
  required: false
- description: "Subset of services to run. Use comma separated list of service ids (eg. 42,1337)"
  value:
  name: SERVICES_LIST
  required: false
- name: CONFIGURATION_LOADER
  description: "When to load configuration. If on gateway start or incoming request. Allowed values are: lazy, boot."
  value: boot
  required: false
- description: "Log level. One of the following: debug, info, notice, warn, error, crit, alert, or emerg."
  name: LOG_LEVEL
  required: false
  value: debug
- description: "Enable path routing. Experimental feature."
  name: PATH_ROUTING
  required: false
  value: "false"
- description: "Enable logging response codes to 3scale."
  value: "false"
  name: RESPONSE_CODES
  required: false
- name: CONFIGURATION_CACHE
  description: "For how long to cache the downloaded configuration in seconds. Can be left empty, 0 or greater than 60."
  value: ""
  required: false
- description: "Redis URL. Required for OAuth2 integration. ex: redis://PASSWORD@127.0.0.1:6379/0"
  name: REDIS_URL
  required: false
- name: MANAGEMENT_API
  description: "Scope of the Management API. Can be disabled, status or debug. At least status required for health checks."
  required: false
  value: "status"
- name: OPENSSL_VERIFY
  description: "Turn on/off the OpenSSL peer verification. Can be set to true/false."
  required: true
  value: "false"
- name: EXTENDED_METRICS
  description: "Enables additional information on Prometheus metrics; some labels will be used with specific information that will provide more in-depth details about APIcast."
  required: false
  value: "true"
