{
 "title": "Software Delivery Performance",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "description": "Lead Time for Change: The time it takes to move from code commited to code deployed in production.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "content": "# Lead Time for Change"
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 }, "content": "# Deployment Frequency" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 }, "content": "# Mean Time to Restore" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 }, "content": "# Change Failure Rate" },
  {
   "title": "Current interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (deploy_timestamp - on(image_sha) group_left commit_timestamp)"
    }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "description": "Negative numbers are good here.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sdp:lead_time:global) - (sdp:lead_time:global offset $__range)) / (sdp:lead_time:global offset $__range)"
    }
   ]
  },
  {
   "title": "Current interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (count_over_time (deploy_timestamp [$__range]) )"
    }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count (count_over_time (deploy_timestamp [$__range]) ) - count (count_over_time (deploy_timestamp [$__range] offset $__range) ) ) / count (count_over_time (deploy_timestamp [$__range] offset $__range) )"
    }
   ]
  },
  {
   "title": "Current Interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "fr:time_to_restore:global" }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((fr:time_to_restore:global ) - (fr:time_to_restore:global  offset $__range)) / (fr:time_to_restore:global  offset $__range)\n"
    }
   ]
  },
  {
   "title": "Current Interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(fr:change_failure_rate [$__range])"
    }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((avg_over_time(fr:change_failure_rate [$__range])) - (avg_over_time(fr:change_failure_rate [$__range] offset $__range) ) ) / (avg_over_time(fr:change_failure_rate [$__range] offset $__range) ) "
    }
   ]
  },
  {
   "title": "Lead Time for Change over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "sdp:lead_time:global" }
   ]
  },
  {
   "title": "Deployments over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (count_over_time (deploy_timestamp [$__range]) )"
    }
   ]
  },
  {
   "title": "MTTR over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "fr:time_to_restore:global" }
   ]
  },
  {
   "title": "Change Failure Rate over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(fr:change_failure_rate [$__range])"
    }
   ]
  }
 ]
}