{
 "title": "Fuse",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(org_apache_camel_ExchangesCompleted{type=\"routes\"},namespace)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"routes\"},container)"
   },
   {
    "name": "routes",
    "label": "Routes",
    "query": "label_values(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",container=\"$container\",type=\"routes\"},route)"
   }
  ]
 },
 "panels": [
  { "title": "Global State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",container='${container}',type=\"routes\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",container='${container}',type=\"routes\"}) by (routes)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",container='${container}',type=\"routes\"})"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",container='${container}',type=\"routes\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",container='${container}',type=\"routes\"})"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - sum(avg_over_time(container_memory_usage_bytes{namespace=\"esb-dev\",container_name=\"changed-document-develop\"}[1m]))by(instance)*100/sum(avg_over_time(container_memory_max_usage_bytes{namespace=\"esb-dev\",container_name=\"changed-document-develop\"}[1m]))by(instance)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - sum(avg_over_time(container_memory_usage_bytes{namespace=\"esb-dev\",container_name=\"changed-document-develop\"}[1m]))by(instance)*100/sum(avg_over_time(container_memory_max_usage_bytes{namespace=\"esb-dev\",container_name=\"changed-document-develop\"}[1m]))by(instance)"
    }
   ]
  },
  { "title": "Route: $routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "routes" },
  {
   "title": "Ex/sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(org_apache_camel_MinProcessingTime{namespace=\"$namespace\", container=\"$container\",type=\"routes\",route='${routes}'} + org_apache_camel_MaxProcessingTime{namespace=\"$namespace\", container=\"$container\",type=\"routes\",route='${routes}'}) / 2"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  { "title": "Route: $routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Ex/sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(org_apache_camel_MinProcessingTime{namespace=\"$namespace\", container=\"$container\",type=\"routes\",route='${routes}'} + org_apache_camel_MaxProcessingTime{namespace=\"$namespace\", container=\"$container\",type=\"routes\",route='${routes}'}) / 2"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  { "title": "Route: $routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ex/sec",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(org_apache_camel_MinProcessingTime{namespace=\"$namespace\", container=\"$container\",type=\"routes\",route='${routes}'} + org_apache_camel_MaxProcessingTime{namespace=\"$namespace\", container=\"$container\",type=\"routes\",route='${routes}'}) / 2"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",container='${container}',type=\"routes\",route='${routes}'})"
    }
   ]
  }
 ]
}