{
 "title": "3Scale",
 "description": "3Scale dashboard",
 "tags": [ "3scale" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(org_apache_camel_ExchangesCompleted{type=\"routes\"},namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nginx_http_connections{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "httpCode",
    "label": "httpCode",
    "query": "label_values(upstream_status, status)"
   },
   { "name": "time_range", "label": "Interval", "query": "1m,5m,15m,30m,1h,2h,1d" }
  ]
 },
 "panels": [
  { "title": "Connections Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Code 200/300",
   "type": "graph",
   "description": "Number of 200/300 http codes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(upstream_status{status=~\"2.*|3.*\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])",
     "legendFormat": "{{pod}}, Code: {{status}}"
    }
   ]
  },
  {
   "title": "Http Code 400/500",
   "type": "graph",
   "description": "Number of 400/500 http codes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(upstream_status{status=~\"4.*|5.*\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])",
     "legendFormat": "{{pod}}, Code: {{status}}"
    }
   ]
  },
  { "title": "Connections details (Numbers)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Http Code $httpCode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "repeat": "httpCode",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(upstream_status{pod=~\"$pod\", status=~\"$httpCode\"})",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Connections details(Graphics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Http Code $httpCode",
   "type": "graph",
   "description": "Number of $httpCode http codes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "httpCode",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(upstream_status{status=~\"$httpCode\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])",
     "legendFormat": "{{pod}}, Code: {{status}}"
    }
   ]
  },
  { "title": "Upstream Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "3Scale Backend Calls Counter",
   "type": "graph",
   "description": "Calls to the 3scale backend",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(threescale_backend_calls{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"2..|3..\"}[$time_range])",
     "legendFormat": "{{pod}},  Code: {{status}}"
    },
    {
     "expr": "-increase(threescale_backend_calls{namespace=~\"$namespace\", pod=~\"$pod\", status!~\"2..|3..\"}[$time_range])",
     "legendFormat": "{{pod}}, Code: {{status}}"
    }
   ]
  },
  {
   "title": "Upstream Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(upstream_status{namespace=~\"$namespace\", status=~\"2..|3..\", pod=~\"$pod\"}[$time_range])",
     "legendFormat": "{{pod}}, Code {{status}}"
    },
    {
     "expr": "-increase(upstream_status{namespace=~\"$namespace\", status!~\"2..|3..\", pod=~\"$pod\"}[$time_range])",
     "legendFormat": "{{pod}}, Code: {{status}}"
    }
   ]
  },
  {
   "title": "Detailed Percentages on total 3scale http connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Percentage of $httpCode http codes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "repeat": "httpCode",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*sum(upstream_status{pod=~\"$pod\", status=~\"$httpCode\"})/sum(upstream_status{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Percentages on total 3scale http connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Percentage of 200/300 http codes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*sum(upstream_status{pod=~\"$pod\", status=~\"2.*|3.*\"})/sum(upstream_status{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Percentage of 400/500 http codes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*sum(upstream_status{pod=~\"$pod\", status=~\"4.*|5.*\"})/sum(upstream_status{pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "Nginx Http Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Total HTTP connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"total\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Accepted HTTP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"accepted\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active HTTP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"active\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reading HTTP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"reading\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Writing HTTP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"writing\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting HTTP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"waiting\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Handled HTTP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"handled\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of nginx-lua-prometheus errors",
   "type": "graph",
   "description": "Number of nginx-lua-prometheus errors",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_metric_errors_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$time_range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Total Response Time Buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Total response time $pod",
   "type": "heatmap",
   "description": "Response times from upstream servers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "total_response_time_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Upstream Response Time Buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Upstream response time $pod",
   "type": "heatmap",
   "description": "Response times from upstream servers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "upstream_response_time_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "OpenResty shared dictionary free space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 }
  },
  {
   "title": "Api Keys",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"api_keys\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"api_keys\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Batched Reports",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"batched_reports\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"batched_reports\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Batched Reports Locks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"batched_reports_locks\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"batched_reports_locks\", pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cached Auths",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"cached_auths\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"cached_auths\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"configuration\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"configuration\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Init",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"init\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"init\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Limiter",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"limiter\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"limiter\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"locks\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"locks\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus Metrics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * openresty_shdict_free_space{dict=\"prometheus_metrics\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"prometheus_metrics\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}