apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      serviceAccountName: amq-broker-operator
      containers:
        - name: amq-broker-operator
          # Replace this with the built image name
          image: 172.30.1.1:5000/openshift/amq-broker-rhel7-operator:0.13
          command:
            - /home/amq-broker-operator/bin/entrypoint
          args:
            # Explicitly set the logging level.
            # Valid values are debug, info, and error
            # from most to least
            - '--zap-level debug'
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "amq-broker-operator"
