apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: broker-amq
  application: broker-amq-app
spec:
  version: 7.6.0
  deploymentPlan:
    size: 1
    image: 172.30.1.1:5000/openshift/amq-broker:7.6
    requireLogin: false
    persistenceEnabled: true
    journalType: nio
    messageMigration: true
  console:
    expose: true
  acceptors:
    - name: artemis
      protocols: CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE
      port: 61616
      sslEnabled: false
      needClientAuth: true
      wantClientAuth: true
      verifyHost: true
      sslProvider: JDK
      sniHost: localhost
      expose: true
      anycastPrefix: jms.topic.
      multicastPrefix: /queue/
    - name: amqp
      protocols: amqp
      port: 5672
      sslEnabled: false
      enabledCipherSuites: SSL_RSA_WITH_RC4_128_SHA,SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
      enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      needClientAuth: true
      wantClientAuth: true
      verifyHost: true
      sslProvider: JDK
      sniHost: localhost
      expose: true
      anycastPrefix: jms.topic.
      multicastPrefix: /queue/
  connectors:
    - name: connector0
      host: localhost
      port: 22222
      sslEnabled: false
      enabledCipherSuites: SSL_RSA_WITH_RC4_128_SHA,SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
      enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      needClientAuth: true
      wantClientAuth: true
      verifyHost: true
      sslProvider: JDK
      sniHost: localhost
      expose: true
  upgrades:
      enabled: false
      minor: false

